from datetime import datetime
from typing import Protocol

from app.models.session import Session
from app.models.user import User


class UserStore(Protocol):
    async def create(self, name: str, email: str, password_hash: str) -> User: ...
    async def find_by_email(self, email: str) -> User | None: ...
    async def find_by_id(self, user_id: str) -> User | None: ...
    async def record_login(self, user_id: str) -> None: ...


class SessionStore(Protocol):
    async def create(
        self,
        user_id: str,
        token_hash: str,
        refresh_jti: str,
        family_id: str,
        expires_at: datetime,
    ) -> Session: ...
    async def find_by_jti(self, refresh_jti: str) -> Session | None: ...
    async def consume(self, refresh_jti: str, token_hash: str) -> Session | None: ...
    async def mark_replacement(self, session_id: str, replacement_id: str) -> None: ...
    async def revoke_by_jti(self, refresh_jti: str) -> None: ...
    async def revoke_family(self, family_id: str) -> None: ...

