import React, { useRef, useState } from "react";
import { AlertTriangle, CheckCircle2, Download, FileSpreadsheet, Layers3, PackageCheck, Trash2, Upload, XCircle } from "lucide-react";

import { Badge, Button, Card, Spinner } from "../components/ui";
import { bulkForgeApi, useBulkJobs, type BulkFormat, type BulkJob } from "../features/bulk-forge";
import { cn } from "../lib/cn";


const statusVariant = (status: BulkJob["status"]): "success" | "warning" | "danger" | "info" => status === "completed" ? "success" : status === "failed" ? "danger" : status === "partial" ? "warning" : "info";

export const BulkForgePage: React.FC = () => {
  const { jobs, isLoading, isUploading, error, create, remove } = useBulkJobs();
  const [file, setFile] = useState<File | null>(null); const [formats, setFormats] = useState<BulkFormat[]>(["png"]); const [dragging, setDragging] = useState(false);
  const inputRef = useRef<HTMLInputElement>(null);
  const chooseFile = (next?: File) => { if (next) setFile(next); };
  const toggleFormat = (format: BulkFormat) => setFormats((current) => current.includes(format) ? current.length === 1 ? current : current.filter((item) => item !== format) : [...current, format]);
  const submit = async () => { if (!file) return; await create(file, formats).then(() => setFile(null)).catch(() => undefined); };
  const downloadTemplate = () => {
    const content = "type,label,url,text,email,subject,body,phone,ssid,password,security,hidden,full_name,organization,latitude,longitude,name,max_scans\nurl,Website,https://example.com,,,,,,,,,,,,,,,\ntext,Welcome message,,Hello IntelliQR,,,,,,,,,,,,,,\n";
    const url = URL.createObjectURL(new Blob([content], { type: "text/csv;charset=utf-8" })); const anchor = document.createElement("a");
    anchor.href = url; anchor.download = "intelliqr-bulk-template.csv"; anchor.click(); URL.revokeObjectURL(url);
  };

  return <div className="space-y-6 animate-fade-in">
    <section className="flex flex-col gap-4 sm:flex-row sm:items-end sm:justify-between"><div><div className="mb-2 flex gap-2"><Badge variant="purple">Milestone 6</Badge><Badge variant="success">Local batch engine</Badge></div><h1 className="text-2xl font-bold text-white sm:text-3xl">BulkForge</h1><p className="mt-1 text-sm text-slate-500">Generate up to 250 validated QR codes from CSV or Excel.</p></div><Button variant="outline" icon={<Download className="h-4 w-4" />} onClick={downloadTemplate}>Download CSV template</Button></section>

    <Card padding="lg"><div className="grid gap-6 lg:grid-cols-[1fr_300px]"><div><button type="button" onClick={() => inputRef.current?.click()} onDragOver={(event) => { event.preventDefault(); setDragging(true); }} onDragLeave={() => setDragging(false)} onDrop={(event) => { event.preventDefault(); setDragging(false); chooseFile(event.dataTransfer.files[0]); }} className={cn("flex min-h-56 w-full flex-col items-center justify-center rounded-2xl border border-dashed px-6 text-center transition-colors", dragging ? "border-violet-400 bg-violet-500/10" : "border-white/12 bg-white/2 hover:border-violet-500/50")}><FileSpreadsheet className="h-10 w-10 text-violet-400" /><p className="mt-4 text-sm font-medium text-slate-300">{file ? file.name : "Drop CSV or XLSX here"}</p><p className="mt-1 text-xs text-slate-600">{file ? `${(file.size / 1024).toFixed(1)} KB selected` : "or click to browse · maximum 5 MB"}</p></button><input ref={inputRef} className="hidden" type="file" accept=".csv,.xlsx,application/vnd.openxmlformats-officedocument.spreadsheetml.sheet" onChange={(event) => { chooseFile(event.target.files?.[0]); event.currentTarget.value = ""; }} /></div>
      <div><h2 className="font-semibold text-white">Export formats</h2><p className="mt-1 text-xs text-slate-600">Each successful row is included in one ZIP.</p><div className="mt-4 space-y-2">{(["png", "svg", "pdf"] as BulkFormat[]).map((format) => <button key={format} type="button" onClick={() => toggleFormat(format)} className={cn("flex w-full items-center justify-between rounded-xl border p-3 text-sm uppercase", formats.includes(format) ? "border-violet-500/35 bg-violet-500/10 text-violet-300" : "border-white/7 text-slate-600")}><span>{format}</span>{formats.includes(format) && <CheckCircle2 className="h-4 w-4" />}</button>)}</div><Button fullWidth className="mt-5" loading={isUploading} disabled={!file} icon={<Upload className="h-4 w-4" />} onClick={() => void submit()}>Start batch</Button></div></div></Card>
    {error && <p role="alert" className="rounded-xl border border-red-500/20 bg-red-500/10 p-4 text-sm text-red-400">{error.message}</p>}

    <section><div className="mb-3 flex items-center gap-2"><Layers3 className="h-4 w-4 text-violet-400" /><h2 className="font-semibold text-white">Batch jobs</h2></div><Card padding="none">{isLoading ? <div className="flex min-h-48 items-center justify-center"><Spinner /></div> : jobs.length === 0 ? <div className="flex min-h-48 flex-col items-center justify-center text-center"><PackageCheck className="h-8 w-8 text-slate-700" /><p className="mt-3 text-sm text-slate-500">No bulk jobs yet</p></div> : <div className="divide-y divide-white/5">{jobs.map((job) => <article key={job.id} className="p-5"><div className="flex flex-col gap-4 lg:flex-row lg:items-start lg:justify-between"><div className="min-w-0 flex-1"><div className="flex flex-wrap items-center gap-2"><p className="truncate font-medium text-slate-200">{job.filename}</p><Badge variant={statusVariant(job.status)} className="capitalize">{job.status}</Badge>{job.formats.map((format) => <Badge key={format}>{format.toUpperCase()}</Badge>)}</div><p className="mt-2 text-xs text-slate-600">{job.processed_rows}/{job.total_rows} processed · {job.succeeded_rows} successful · {job.failed_rows} failed</p><div className="mt-3 h-2 overflow-hidden rounded-full bg-white/5"><div className={cn("h-full rounded-full transition-all duration-500", job.status === "failed" ? "bg-red-500" : "bg-gradient-to-r from-violet-500 to-blue-500")} style={{ width: `${job.progress_percentage}%` }} /></div>{job.errors.length > 0 && <div className="mt-3 rounded-xl border border-amber-500/15 bg-amber-500/5 p-3">{job.errors.slice(0, 4).map((item) => <p key={`${item.row}-${item.message}`} className="text-xs text-amber-400"><AlertTriangle className="mr-1 inline h-3 w-3" />{item.row ? `Row ${item.row}: ` : ""}{item.message}</p>)}</div>}</div><div className="flex gap-2">{job.download_url && <Button size="sm" icon={<Download className="h-4 w-4" />} onClick={() => void bulkForgeApi.download(job.id)}>Download ZIP</Button>}<Button aria-label="Delete job" size="sm" variant="danger" icon={<Trash2 className="h-4 w-4" />} disabled={job.status === "processing" || job.status === "queued"} onClick={() => void remove(job.id)} /></div></div><p className="mt-3 flex items-center gap-1 text-[11px] text-slate-700">{job.status === "failed" ? <XCircle className="h-3 w-3" /> : <CheckCircle2 className="h-3 w-3" />}Created {new Date(job.created_at).toLocaleString()}</p></article>)}</div>}</Card></section>
    <p className="text-xs leading-relaxed text-slate-700">Required columns depend on type: URL uses <code>url</code>, text uses <code>text</code>, email uses <code>email</code>, phone uses <code>phone</code>, Wi-Fi uses <code>ssid</code>, contact uses <code>full_name</code>, and location uses <code>latitude</code> plus <code>longitude</code>. Generated records remain available in Dashboard even if the batch job or ZIP is deleted.</p>
  </div>;
};
