import React, { useRef, useState } from "react";
import { Clock3, Copy, Download, FileLock2, History, Pause, Play, QrCode, ShieldCheck, Trash2, Upload } from "lucide-react";

import { Badge, Button, Card, Input, Spinner } from "../components/ui";
import { qrGeneratorApi } from "../features/qr-generator";
import { shareVaultApi, useShares, type ShareAccessMode, type ShareDownloadEvent } from "../features/share-vault";
import { cn } from "../lib/cn";


const fieldClass = "w-full rounded-xl border border-white/8 bg-white/4 px-4 py-3 text-sm text-slate-200 focus:border-violet-500/60 focus:outline-none";
const sizeLabel = (bytes: number) => bytes >= 1024 * 1024 ? `${(bytes / 1024 / 1024).toFixed(1)} MB` : `${(bytes / 1024).toFixed(1)} KB`;

export const ShareVaultPage: React.FC = () => {
  const { items, isLoading, isCreating, error, create, update, remove } = useShares();
  const inputRef = useRef<HTMLInputElement>(null); const [file, setFile] = useState<File | null>(null);
  const [mode, setMode] = useState<ShareAccessMode>("public"); const [password, setPassword] = useState(""); const [emails, setEmails] = useState("");
  const [expiresAt, setExpiresAt] = useState(""); const [maxDownloads, setMaxDownloads] = useState(""); const [history, setHistory] = useState<Record<string, ShareDownloadEvent[]>>({});
  const submit = async () => { if (!file) return; await create({ file, accessMode: mode, password: password || undefined, allowedEmails: emails || undefined, expiresAt: expiresAt || undefined, maxDownloads: maxDownloads ? Number(maxDownloads) : undefined }).then(() => { setFile(null); setPassword(""); setEmails(""); }).catch(() => undefined); };
  const showHistory = async (id: string) => {
    if (history[id]?.length) { setHistory((current) => ({ ...current, [id]: [] })); return; }
    const result = await shareVaultApi.downloads(id); setHistory((current) => ({ ...current, [id]: result.items }));
  };

  return <div className="space-y-6 animate-fade-in">
    <section><div className="mb-2 flex gap-2"><Badge variant="success">AES encrypted</Badge></div><h1 className="text-2xl font-bold text-white sm:text-3xl">ShareVault</h1><p className="mt-1 text-sm text-slate-500">Share protected local files through controlled QR access.</p></section>
    <Card padding="lg"><div className="grid gap-6 xl:grid-cols-[1fr_1fr]"><div><button type="button" onClick={() => inputRef.current?.click()} className="flex min-h-52 w-full flex-col items-center justify-center rounded-2xl border border-dashed border-white/12 bg-white/2 px-6 text-center transition-colors hover:border-violet-500/50"><FileLock2 className="h-10 w-10 text-violet-400" /><p className="mt-4 text-sm font-medium text-slate-300">{file?.name ?? "Choose a protected file"}</p><p className="mt-1 text-xs text-slate-600">{file ? sizeLabel(file.size) : "PDF, images, video, text, CSV, DOCX, XLSX, PPTX · 25 MB"}</p></button><input ref={inputRef} type="file" className="hidden" accept=".pdf,.png,.jpg,.jpeg,.webp,.gif,.mp4,.webm,.mov,.txt,.csv,.docx,.xlsx,.pptx,.odt" onChange={(event) => { setFile(event.target.files?.[0] ?? null); event.currentTarget.value = ""; }} /></div>
      <div><p className="mb-2 text-sm font-medium text-slate-300">Access policy</p><div className="grid grid-cols-2 gap-2">{(["public", "password", "authenticated", "private"] as ShareAccessMode[]).map((value) => <button type="button" key={value} onClick={() => setMode(value)} className={cn("rounded-xl border p-2.5 text-sm capitalize", mode === value ? "border-violet-500/40 bg-violet-500/10 text-violet-300" : "border-white/7 text-slate-600")}>{value === "authenticated" ? "Members" : value}</button>)}</div>{mode === "password" && <div className="mt-3"><Input label="Share password" type="password" minLength={8} value={password} onChange={(event) => setPassword(event.target.value)} /></div>}{mode === "private" && <label className="mt-3 block text-sm text-slate-300">Allowed emails<textarea rows={2} className={fieldClass} value={emails} onChange={(event) => setEmails(event.target.value)} placeholder="client@example.com" /></label>}<div className="mt-3 grid gap-3 sm:grid-cols-2"><Input label="Expiry (optional)" type="datetime-local" value={expiresAt} onChange={(event) => setExpiresAt(event.target.value)} /><Input label="Download limit" type="number" min={1} value={maxDownloads} onChange={(event) => setMaxDownloads(event.target.value)} placeholder="Unlimited" /></div><Button fullWidth className="mt-4" loading={isCreating} disabled={!file || (mode === "password" && password.length < 8) || (mode === "private" && !emails.trim())} icon={<Upload className="h-4 w-4" />} onClick={() => void submit()}>Encrypt and create QR</Button></div></div></Card>
    {error && <p role="alert" className="rounded-xl border border-red-500/20 bg-red-500/10 p-4 text-sm text-red-400">{error.message}</p>}
    <section><div className="mb-3 flex items-center gap-2"><ShieldCheck className="h-4 w-4 text-violet-400" /><h2 className="font-semibold text-white">Protected files</h2></div><Card padding="none">{isLoading ? <div className="flex min-h-48 items-center justify-center"><Spinner /></div> : items.length === 0 ? <div className="flex min-h-48 flex-col items-center justify-center"><FileLock2 className="h-8 w-8 text-slate-700" /><p className="mt-3 text-sm text-slate-500">No shared files yet</p></div> : <div className="divide-y divide-white/5">{items.map((item) => <article key={item.id} className="p-5"><div className="flex flex-col gap-4 lg:flex-row lg:items-start lg:justify-between"><div className="min-w-0 flex-1"><div className="flex flex-wrap items-center gap-2"><p className="truncate font-medium text-slate-200">{item.filename}</p><Badge variant={item.status === "active" ? "success" : "warning"} className="capitalize">{item.status.replaceAll("_", " ")}</Badge><Badge variant="purple" className="capitalize">{item.access_mode}</Badge></div><p className="mt-2 break-all text-xs text-slate-600">{item.share_url}</p><p className="mt-1 text-xs text-slate-700">{sizeLabel(item.size)} · {item.download_count}{item.max_downloads ? `/${item.max_downloads}` : ""} downloads{item.expires_at ? ` · Expires ${new Date(item.expires_at).toLocaleString()}` : ""}</p></div><div className="flex flex-wrap gap-2"><Button size="sm" variant="outline" icon={<Copy className="h-4 w-4" />} onClick={() => void navigator.clipboard.writeText(item.share_url)}>Copy link</Button><Button size="sm" variant="outline" icon={<QrCode className="h-4 w-4" />} onClick={() => void qrGeneratorApi.saveDownload(item.qr_generation_id, "png")}>QR PNG</Button><Button size="sm" variant="outline" icon={<History className="h-4 w-4" />} onClick={() => void showHistory(item.id)}>History</Button><Button size="sm" variant="outline" icon={item.is_active ? <Pause className="h-4 w-4" /> : <Play className="h-4 w-4" />} onClick={() => void update(item.id, { is_active: !item.is_active })}>{item.is_active ? "Pause" : "Activate"}</Button><Button aria-label="Delete shared file" size="sm" variant="danger" icon={<Trash2 className="h-4 w-4" />} onClick={() => void remove(item.id)} /></div></div>{history[item.id] && history[item.id].length > 0 && <div className="mt-4 rounded-xl border border-white/6 bg-white/2 p-3"><p className="mb-2 text-xs font-semibold uppercase tracking-wider text-slate-600">Recent downloads</p>{history[item.id].slice(0, 8).map((event) => <p key={event.id} className="flex items-center gap-2 py-1 text-xs text-slate-500"><Clock3 className="h-3 w-3" />{event.device_type} · {event.browser} / {event.operating_system} · {event.city}, {event.country} · {new Date(event.downloaded_at).toLocaleString()}</p>)}</div>}</article>)}</div>}</Card></section>
    <p className="text-xs text-slate-700">Files are encrypted before local storage. Uploads are restricted by extension and signature, but ShareVault is not an antivirus scanner. Share files only with recipients you trust.</p>
  </div>;
};
